on:
  push:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Latest PowerShell
      shell: pwsh
      run: |
            dotnet tool install --global PowerShell
            $content = Get-Content -Path $env:GITHUB_PATH
            $HOME + "/.dotnet/tools`r`n" + $content | Set-Content -Path $env:GITHUB_PATH -Encoding utf8
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: pwsh7
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: pwsh7
    - name: Build
      run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY -SkipPublish -AutoVersion
      shell: pwsh7
      env:
        APIKEY: ${{ secrets.ApiKey }}